Repository TYPO3-Documentation/TYPO3CMS-Tutorial-Editors, pull requests merged in 2023-08, with the labels that each got.

#126 [TASK] Revise page types chapter
  Documentation/Pages/PageTypes/Index.rst
Labels: backport 11.5, backport 12.4

#130 [TASK] #101137 - Remove pages.doktype 255 / recycler
  Documentation/Pages/PageTypes/Index.rst
  Documentation/Settings.cfg
Labels: changelog

#133 Overhaul Page properties
  Documentation/Pages/PageProperties/Index.rst
Labels: backport 12.4
