Repository TYPO3-Documentation/TYPO3CMS-Tutorial-Editors, pull requests merged in 2024-04, with the labels that each got.

#154 [BUGFIX] Add missing reference for concepts
  Documentation/Index.rst
  Documentation/Localization.ru_RU/Index.rst
Labels: backport 11.5, backport 12.4

#155 [BUGFIX] Remove meta menu from subpage
  Documentation/Concepts/Index.rst
  Documentation/Localization.ru_RU/Concepts/Index.rst
Labels: backport 11.5, backport 12.4

#156 [FEATURE] #87889 - Make backend URL configurable
  Documentation/Localization.ru_RU/Login/Index.rst
  Documentation/Login/Index.rst
Labels: changelog

#163 [TASK] Mention user permissions defining available page properties
  Documentation/Pages/PageProperties/Index.rst
Labels: backport 11.5, backport 12.4

#161 [TASK] Split up "Help within TYPO3" chapter
  Documentation/HelpInside/BackendSearch/Index.rst
  Documentation/HelpInside/Index.rst
  Documentation/HelpInside/OnlineDocumentation/Index.rst
  Documentation/HelpInside/Tooltips/Index.rst
  Documentation/Localization.ru_RU/HelpInside/BackendSearch/Index.rst
  Documentation/Localization.ru_RU/HelpInside/Index.rst
  Documentation/Localization.ru_RU/HelpInside/OnlineDocumentation/Index.rst
  Documentation/Localization.ru_RU/HelpInside/Tooltips/Index.rst
Labels: content structure, backport 12.4

#162 [FEATURE] #97667 - Add keyboard support for Multiselect
  Documentation/HelpInside/KeyboardCommands/Index.rst
  Documentation/Images/ManualScreenshots/ContentElements/Folder.png
  Documentation/Images/ManualScreenshots/ContentElements/Group.png
  Documentation/Images/ManualScreenshots/ContentElements/SelectMultipleSideBySide.png
  Documentation/Localization.ru_RU/HelpInside/KeyboardCommands/Index.rst
  Documentation/Localization.ru_RU/Images/ManualScreenshots/ContentElements/Folder.png
  Documentation/Localization.ru_RU/Images/ManualScreenshots/ContentElements/Group.png
  Documentation/Localization.ru_RU/Images/ManualScreenshots/ContentElements/SelectMultipleSideBySide.png
Labels: backport 12.4, changelog
